// sanity/schemas/projectProposal.js
import React from 'react'

export default {
  name: 'projectProposal',
  title: 'Project Proposals',
  type: 'document',
  fields: [
    {
      name: 'status',
      title: 'Project Status',
      type: 'string',
      options: {
        list: [
          { title: 'Pending Review', value: 'pending' },
          { title: 'In Review', value: 'in-review' },
          { title: 'Active - Seeking Contributors', value: 'active-seeking' },
          { title: 'Active - In Progress', value: 'active-progress' },
          { title: 'Completed', value: 'completed' },
          { title: 'Rejected', value: 'rejected' },
        ],
        layout: 'radio',
      },
      initialValue: 'pending',
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'boardComments',
      title: 'Board Comments & Feedback',
      description: 'Comments for the proposer. They will be notified of any updates.',
      type: 'array',
      of: [{ type: 'block' }],
    },
    {
      name: 'trackingId',
      title: 'Tracking ID',
      type: 'string',
      readOnly: true,
      description: 'The unique ID for the proposal status page.',
    },
    {
      name: 'proposerName',
      title: 'Proposer Name',
      type: 'string',
      readOnly: true,
    },
    {
      name: 'proposerEmail',
      title: 'Proposer Email',
      type: 'string',
      readOnly: true,
    },
    {
      name: 'projectName',
      title: 'Project Name',
      type: 'string',
      readOnly: true,
    },
    {
      name: 'description',
      title: 'Description',
      type: 'text',
      readOnly: true,
    },
    {
      name: 'techStack',
      title: 'Proposed Tech Stack',
      type: 'string',
      readOnly: true,
    },
    {
      name: 'timeline',
      title: 'Estimated Timeline',
      type: 'string',
      readOnly: true,
    },
    {
      name: 'goals',
      title: 'Goals & Success Metrics',
      type: 'text',
      readOnly: true,
    },
    {
      name: 'estimatedBudget',
      title: 'Estimated Budget ($)',
      type: 'number',
      readOnly: true,
    },
    {
      name: 'fundingSource',
      title: 'Funding Source',
      type: 'string',
      readOnly: true,
    },
    {
      name: 'budgetBreakdown',
      title: 'Budget Breakdown',
      type: 'text',
      readOnly: true,
    },
    {
      name: 'specialRequests',
      title: 'Special Requests',
      type: 'text',
      readOnly: true,
    },
    {
      name: 'teamMembers',
      title: 'Proposed Team Members',
      type: 'array',
      of: [{ type: 'reference', to: { type: 'member' } }],
      readOnly: true,
    },
    {
      name: 'presentation',
      title: 'Presentation File',
      type: 'file',
      readOnly: true,
    },
    {
      name: 'presentationTime',
      title: 'Proposed Presentation Time',
      type: 'datetime',
      readOnly: true,
    },
    {
      name: 'convertedToActiveProject',
      title: 'Converted to Active Project',
      type: 'reference',
      to: [{ type: 'activeProject' }],
      description: 'Reference to the active project created from this proposal.',
    },
    {
      name: 'conversionDate',
      title: 'Conversion Date',
      type: 'datetime',
      description: 'When this proposal was converted to an active project.',
    },
    // Active project fields - only relevant when status is active-*
    {
      name: 'maxContributors',
      title: 'Maximum Contributors',
      type: 'number',
      description: 'Maximum number of people who can join this project.',
      initialValue: 5,
      hidden: ({ document }) => !document?.status?.startsWith('active'),
    },
    {
      name: 'currentContributors',
      title: 'Current Contributors',
      type: 'array',
      of: [{ type: 'reference', to: { type: 'member' } }],
      description: 'People currently working on this project.',
      hidden: ({ document }) => !document?.status?.startsWith('active'),
    },
    {
      name: 'skillsNeeded',
      title: 'Skills Needed',
      type: 'array',
      of: [{ type: 'string' }],
      description: 'What skills are we looking for in contributors?',
      hidden: ({ document }) => !document?.status?.startsWith('active'),
    },
    {
      name: 'difficultyLevel',
      title: 'Difficulty Level',
      type: 'string',
      options: {
        list: [
          { title: 'Beginner Friendly', value: 'beginner' },
          { title: 'Intermediate', value: 'intermediate' },
          { title: 'Advanced', value: 'advanced' },
          { title: 'Mixed Levels', value: 'mixed' },
        ],
        layout: 'radio',
      },
      initialValue: 'intermediate',
      hidden: ({ document }) => !document?.status?.startsWith('active'),
    },
    {
      name: 'timeCommitment',
      title: 'Time Commitment',
      type: 'string',
      description: 'Expected hours per week (e.g., "3-5 hours/week")',
      initialValue: '3-5 hours/week',
      hidden: ({ document }) => !document?.status?.startsWith('active'),
    },
    {
      name: 'meetingSchedule',
      title: 'Meeting Schedule',
      type: 'string',
      description: 'When does the team meet? (e.g., "Weekly Fridays 6PM")',
      hidden: ({ document }) => !document?.status?.startsWith('active'),
    },
    {
      name: 'communicationChannel',
      title: 'Communication Channel',
      type: 'string',
      description: 'Where does the team communicate? (e.g., "Discord #project-name")',
      hidden: ({ document }) => !document?.status?.startsWith('active'),
    },
    {
      name: 'projectImage',
      title: 'Project Image',
      type: 'image',
      options: { hotspot: true },
      description: 'Main image for the project (mockups, diagrams, etc.)',
      hidden: ({ document }) => !document?.status?.startsWith('active'),
    },
  ],
  preview: {
    select: {
      title: 'projectName',
      subtitle: 'proposerName',
      status: 'status',
    },
    prepare({ title, subtitle, status }) {
      const statusEmoji = {
        pending: '⏳',
        'in-review': '👀',
        'active-seeking': '🔍',
        'active-progress': '🚀',
        completed: '✅',
        rejected: '❌',
      };
      return {
        title,
        subtitle: `by ${subtitle}`,
        media: <span style={{ fontSize: '1.5rem' }}>{statusEmoji[status] || '📄'}</span>,
      };
    },
  },
  orderings: [
    {
      title: 'Presentation Time, Newest First',
      name: 'presentationTimeDesc',
      by: [{ field: 'presentationTime', direction: 'desc' }],
    },
  ],
};